version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    # volumes:
    #   - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    #   - /etc/letsencrypt/archive/:/etc/nginx/ssl/
    networks:
      - laravel-app
    ports:
      - "80:80"
      - "443:443"

  postgresql:
    image: postgres
    volumes:
      - /postgres:/var/lib/postgresql/data
      - /docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - laravel-app

networks:
  laravel-app:
